[package]
name = "holium-rust-sdk"
version = "0.1.0"
authors = ["tchataigner <contact@polyphene.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_derive = "1.0"
serde_json = { version = "1.0.64" }

[workspace]