# Basic deployment workflow:
#   - `cargo workspaces publish --from-git --token ***`: For every crate in our workspace, publish it on crates.io

on:
  push:
    branches:
      - main

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-workspaces
      - uses: actions-rs/cargo@v1
        if: steps.cache-deps.outputs.cache-hit != 'true'
        with:
          command: install
          args: cargo-workspaces
      - uses: actions-rs/cargo@v1
        with:
          command: workspaces
          args: publish --from-git --token ${{secrets.CARGO_TOKEN}}
